version: "3.8"

services: 
  devenv:
    container_name: i-wanna-5000-trillion-yen-devenv
    hostname: devenv
    build: .
    ports: 
      - 8000:8000
    volumes: 
      - ./:/usr/src
    tty: true
